config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'groups#index'
  resources :users, only: [:index, :edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json' }
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :messages
  has_many :group_users
  has_many :users, through: :group_users
  
  validates :name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.content? ? last_message.content : "画像が投稿されています"
    else
      "まだメッセージはありません"
    end
  end
end

app/models/group_user.rb
class GroupUser < ApplicationRecord
  belongs_to :group
  belongs_to :user
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :group
  belongs_to :user
  mount_uploader :image, ImageUploader
  validates :content, presence: true, unless: :image?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :messages
  has_many :group_users
  has_many :groups, through: :group_users
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    # ルーティングでの設定によりparamsの中にgroup_idというキーでグループのidが入るので、これを元にDBからグループを取得する
    group = Group.find(params[:group_id])
    # ajaxで送られてくる最後のメッセージのid番号を変数に代入
    last_message_id = params[:id].to_i
    # 取得したグループでのメッセージ達から、idがlast_message_idよりも新しい(大きい)メッセージ達のみを取得
    @messages = group.messages.includes(:user).where("id > #{last_message_id}")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: [:update, :edit]

  def index
    @group = Group.new
  end
  
  def new
    @group = Group.new
    @group.users << current_user
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to root_path, notice: '赤ちゃんを登録しました'
    else
      render :new
    end
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: "情報を編集しました"
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:name, :birthday, :icon, :image, :meimei, :mhug, :phug, :fphoto, :imhome, :finger, :bathing, :diapers, :hund, :walking, :bathingwith1, :sleepingface1, :discovery, :cream, :saycheese1, :neck, :bathingwith2, :get, :tooth, :roll, :babyfood, :brush, :sleepingface2, :saycheese2, :high, :mam, :high2, :looking, :sit, :stand, :high3, :straw, :sleepingface3, :saycheese3, :imitate, :go, :hair, :katikati, :follow, :pause, :walk, :yam, :sleepingface4, :saycheese4, :imitate2, {user_ids: [] })
  end

  def set_group
    @group = Group.find(params[:id])
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.create(message_params)
      respond_to do |format|
        if @message.save
          format.html { redirect_to group_messages_path, notice: "メッセージを送信しました" }
          format.json
        else
          @messages = @group.messages.includes(:user)
          flash.now[:alert] = 'メッセージを入力してください。'
          render :index
        end
      end
  end

  private

  def message_params
    params.require(:message).permit(:content, :image).merge(user_id: current_user.id)
  end

  def set_group
    @group = Group.find(params[:group_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    return nil if params[:keyword] == ""
    @users = User.where(['name LIKE ?', "%#{params[:keyword]}%"] ).where.not(id: current_user.id).limit(10)
      respond_to do |format|
        format.html
        format.json
    end
  end

  def edit
    
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end
  def set_group
    @group = Group.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_error.html.haml
.selectpage
  .selectpage_top
    %img#error_photo{:src => '/error/kumausagi.png'}/
  .selectpage_message
    まず赤ちゃんを選択しよう

app/views/groups/_form.html.haml
= form_for @group do |f|
  - if group.errors.any?
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :name, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :name, class: 'chat__group_name chat-group-form__input', placeholder: 'おなまえ'
  .chat-group-form__field
    .chat-group-form__field--left
      = f.label :birthday, class: 'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :birthday, class: 'chat__group_birthday chat-group-form__input', placeholder: 'お誕生日'
  .chat-group-form__field
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group"} アイコン写真
    .chat-group-form__field--right
      = f.label :icon, class: "album_update" do
        = f.text_field :icon, placeholder: "Image Url"

  .chat-group-form__field
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group"} 命名写真
    .chat-group-form__field--right
      = f.label :meimei, class: "album_update" do
        = f.text_field :meimei, placeholder: "Image Url"

  .chat-group-form__field
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group"} ベストショット
    .chat-group-form__field--right
      = f.label :image, class: "album_update" do
        = f.text_field :image, placeholder: "Image Url"


  .chat-group-form__field
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_家族を追加"} 家族を追加
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        %input#user-search-field.chat-group-form__input{placeholder: "家族の名前を入力してください", :type => "text"}/
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      %label.chat-group-form__label{for: "chat_group_メンバー"} メンバー
    .chat-group-form__field--right
      #chat-group-users.js-add-user
        .chat-group-user.clearfix.js-chat-member
          %input{name: "group[user_ids][]", type: "hidden", value: current_user.id}
          %p.chat-group-user__name= current_user.name

        - group.users.each do |user|
          - if current_user.name != user.name
            .chat-group-user.clearfix.js-chat-member
              %input{name: "group[user_ids][]", type: "hidden", value: user.id}
              %p.chat-group-user__name
                = user.name 
              %a.user-search-remove.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn
                削除
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn'

app/views/groups/_setting.html.haml
.container.ops-main
  .row
    .col-md-12
      %h3.ops-title 赤ちゃんたち
  .row
    .col-md-11.col-md-offset-1.baby_groups
      %table.table.text-center
        %tr
          %th.text-center おなまえ
          %th.text-center お誕生日
          %th.text-center 写真
          -# %th.text-center 削除
          - current_user.groups.each do |group|
            .baby_group
            %tr
              %td
                =link_to group_messages_path(group) do
                  = group.name
              %td
                = group.birthday
              %td
                - if group.icon?
                  %img.setting_photo{:src => group.icon}/
                - else
                  .none_photo_set
                    %img.setting_photo{:src => '/error/akatyan02.png'}/
              -# %td
              -#   %form{:action => "/group/group.id", :method => "post"}
              -#     %input{:name => "_method", :type => "hidden", :value => "DELETE"}/
              -#     %input{:name => "_token", :type => "hidden", :value => "{{ csrf_token() }}"}/
              -#     %button.btn.btn-xs.btn-danger{"aria-label" => "Left Align", :type => "submit"}
              -#       %span.glyphicon.glyphicon-trash
  .row
    = link_to new_group_path, class: "new_btn" do
      %button.btn.btn-default 赤ちゃんが生まれたよ
  .row
    .setting_underbox
      %button.btn.readme_btn このアプリの使い方
  .readme.hide
    .readme_box
      使い方<br>
      1. 「赤ちゃんが生まれたよ」ボタンを押して、赤ちゃんの情報を登録してください。(編集可能)<br>
      2. 追加したい家族がいれば、同様に登録をし、家族を追加のところに名前を入力すると<br>
      候補が出るので、選択して追加してください。<br>
      3. 赤ちゃんの登録が終わったら名前をクリック<br>
      4.TopPageの左上がアイコン、そのしたが命名写真、そして真ん中に大きくベストショット写真が表示されます。<br>
      5.編集したい場合は、命名写真の下側にある「編集」ボタンを押してください。<br>
      6.家族の編集も同様にこのボタンから行います。<br>
      7.タブにはそれぞれ月齢が設定されています。クリックすると、それぞれのイベントごとに写真を投稿できるようになっています。<br>
      投稿には右下の「編集」ボタンをクリックすることで可能です。<br>
      8.「アルバム」タブはコメントをつけて自由に投稿することができます。<br>
      9.ログアウトは画面右上の、ご自身のお名前をクリックすることで可能です。<br>
    %h1 それでは"HappyLife"をお送りください

app/views/groups/_tweet.html.haml
.content_post{:style => "background-image: url(#{tweet.image});"}
  .more
    %span= image_tag 'arrow_top.png'
    %ul.more_list
      %li
        = link_to '詳細', "/tweets/#{tweet.id}", method: :get
      %li
        - if user_signed_in? && current_user.id == tweet.user_id
          = link_to '編集', "/tweets/#{tweet.id}/edit", method: :get
          %li
            = link_to '削除', "/tweets/#{tweet.id}", method: :delete
  = simple_format(tweet.text)
  %span.name
    %a{:href => "/users/#{tweet.user.id}"}
      %span 投稿者
      = tweet.user.nickname

app/views/groups/_user_edit.html.haml
.wrap1
  .cloud-wrap1
    .cloud
      .textbox1
        .text1
          =link_to edit_user_path(current_user), class: "edit_btn" do
            = current_user.name

app/views/groups/edit.html.haml
.chat-group-form
  %h1 赤ちゃん情報編集
  = render partial: "form", locals: {group: @group}

app/views/groups/index.html.haml
%body.body
  %header
    %h1.head Baby memorY
    = render 'user_edit'

  %ul.tab
    %li.select TOP Page
    %li ０〜2ヶ月
    %li ３〜5ヶ月
    %li ６〜8ヶ月
    %li ９〜11ヶ月
    %li １歳〜
    %li アルバム
    %li 設定
  %ul.content
    %li= render 'setting'
    %li.hide= render 'error'
    %li.hide= render 'error'
    %li.hide= render 'error'
    %li.hide= render 'error'
    %li.hide= render 'error'
    %li.hide= render 'error'
    %li.hide= render 'setting'
  %footer.footer Copyright BabymemorY 2019.

app/views/groups/layout.html.haml
%head
  %title Baby memorY
  %link{:href => "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css", :rel => "stylesheet"}/
  %link{:href => "/css/sass/reset.scss", :rel => "stylesheet"}/
  %link{:href => "/css/sass/tab.scss", :rel => "stylesheet"}/
  %link{:href => "/css/sass/main.scss", :rel => "stylesheet"}/
  %link{:href => "/css/sass/sidebar.scss", :rel => "stylesheet"}/
  %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"}
  %script{:src => "js/script.js"}
%body
  %p
    {{--
    %script{:src => "js/aa.js"}
    \--}}
    %header
      %h1.head Baby mamorY
  %ul.tab
    %li.select TOP Page
    %li ０〜2ヶ月
    %li ３〜5ヶ月
    %li ６〜8ヶ月
    %li ９〜11ヶ月
    %li １歳〜
    %li アルバム
    %li 設定
  %ul.content
    %li @yield('top')
    %li.hide @yield('photo02')
    %li.hide @yield('photo35')
    %li.hide @yield('photo68')
    %li.hide @yield('photo911')
    %li.hide @yield('photo1')
    %li.hide @yield('otheralbum')
    %li.hide @yield('setting')

app/views/groups/new.html.haml
.chat-group-form
  %h1 赤ちゃんが生まれたよ
  = render 'form', { group: @group }

app/views/groups/test1.htmi.erb
<% if @user.image? %>
  <%= image_tag @user.image.url %>
<% else %>
  <%= image_tag noimage.gif %>
<% end %>

app/views/layouts/_links.html.haml
- if controller_name != 'sessions'
  = link_to "Log in", new_session_path(resource_name), class: 'btn'
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  = link_to "Sign up", new_registration_path(resource_name), class: 'btn'
  %br/

app/views/layouts/_notifications.html.haml
.notification
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", 'http-equiv': "Content-Type"}/
    %title BabymemorY
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
  %body
    = render 'layouts/notifications'
    = yield

app/views/messages/_album02.html.haml
.album
  .album_top
    .album_top_title
      = @group.name
      が生まれてから2ヶ月までのアルバム
      .album_editbtn
        %button.album_edit.btn 編集
  .album_contents
    .album_main
      .album_main_content
        .album_main_content_img
        - if @group.mhug?
          %img.album_photo{:src => @group.mhug}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
      .album_main_content
        .album_main_content_img
        - if @group.phug?
          %img.album_photo{:src => @group.phug}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
    .album_main
      .album_main_title
        初めてのママだっこ
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :mhug, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
      .album_main_title
        初めてのパパだっこ
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :phug, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
    .album_main
      .album_main_content
        .album_main_content_img
        - if @group.fphoto?
          %img.album_photo{:src => @group.fphoto}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
      .album_main_content
        .album_main_content_img
        - if @group.imhome?
          %img.album_photo{:src => @group.imhome}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
    .album_main
      .album_main_title
        初めての家族写真
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :fphoto, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
      .album_main_title
        ようこそ我が家へ！
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :imhome, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
    .album_main
      .album_main_content
        .album_main_content_img
        - if @group.finger?
          %img.album_photo{:src => @group.finger}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
      .album_main_content
        .album_main_content_img
        - if @group.bathing?
          %img.album_photo{:src => @group.bathing}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
    .album_main
      .album_main_title
        指をぎゅっと掴まれた
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :finger, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
      .album_main_title
        沐浴デビュー
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :bathing, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
    .album_main
      .album_main_content
        .album_main_content_img
        - if @group.diapers?
          %img.album_photo{:src => @group.diapers}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
      .album_main_content
        .album_main_content_img
        - if @group.hund?
          %img.album_photo{:src => @group.hund}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
    .album_main
      .album_main_title
        初めてのオムツ替え
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :diapers, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
      .album_main_title
        小さなおてて
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :hund, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'

    .album_main
      .album_main_content
        .album_main_content_img
        - if @group.walking?
          %img.album_photo{:src => @group.walking}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
      .album_main_content
        .album_main_content_img
        - if @group.bathingwith1?
          %img.album_photo{:src => @group.bathingwith1}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
    .album_main
      .album_main_title
        お散歩デビュー
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :walking, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
      .album_main_title
        一緒にお風呂
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :bathingwith1, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'

app/views/messages/_album1.html.haml
.album
  .album_top
    .album_top_title
      = @group.name
      の１歳〜のアルバム
      .album_editbtn
        %button.album_edit.btn 編集
        
  .album_contents
    .album_main
      .album_main_content
        .album_main_content_img
        - if @group.follow?
          %img.album_photo{:src => @group.follow}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
      .album_main_content
        .album_main_content_img
        - if @group.pause?
          %img.album_photo{:src => @group.pause}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
    .album_main
      .album_main_title
        パパとママの後をついてくよ
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :follow, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
      .album_main_title
        つかまり立ちでポーズ
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :pause, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'

    .album_main
      .album_main_content
        .album_main_content_img
        - if @group.walk?
          %img.album_photo{:src => @group.walk}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
      .album_main_content
        .album_main_content_img
        - if @group.yam?
          %img.album_photo{:src => @group.yam}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
    .album_main
      .album_main_title
        つたい歩きができました
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :walk, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
      .album_main_title
        手づかみ食べでおいし〜い
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :yam, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'

    .album_main
      .album_main_content
        .album_main_content_img
        - if @group.sleepingface4?
          %img.album_photo{:src => @group.sleepingface4}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
      .album_main_content
        .album_main_content_img
        - if @group.saycheese4?
          %img.album_photo{:src => @group.saycheese4}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
    .album_main
      .album_main_title
        可愛い寝顔
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :sleepingface4, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
      .album_main_title
        こっちむーいて
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :saycheese4, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'

    .album_main
      .album_main_content
        .album_main_content_img
        - if @group.imitate2?
          %img.album_photo{:src => @group.imitate2}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
      .album_main_content
        .album_main_content_img
        - if @group.katikati?
          %img.album_photo{:src => @group.katikati}/
        - else
          .none_photo
            %img.album_none{:src => '/error/akatyan02.png'}/
    .album_main
      .album_main_title
        まねっこまねっこ
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :imitate2, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'
      .album_main_title
        両手に持ってカチカチ
        .album_updatebtn.hide
          = form_for(@group, local: true) do |f|
            = f.label :album_img, class: "album_update" do
              = f.text_field :katikati, placeholder: "Image Url"
              = f.submit '送信', class: 'album_update, btn'

app/views/messages/_main_chat.html.haml
.main_center
  = render @messages
.main_bottom
  = form_for [@group, @message] do |f|
    .main_bottom_textbox
      .main_bottom_textbox_text
        = f.text_field :content, class: 'form__message', placeholder: 'type a message', style: "border: none"
      .main_bottom_textbox_img
        = f.label :image, class: "input-box__image" do
          = fa_icon 'picture-o'
          = f.file_field :image, class: 'file'
    .main_bottom_send
      = f.submit 'Send', class: 'form__submit'

app/views/messages/_message.html.haml
.main_center_thread{"data-message-id": "#{message.id}"}
  .main_center_thread_upper-message
    .main_center_thread_upper-message_name
      = message.user.name
    .main_center_thread_upper-message_date
      = message.created_at.strftime("%Y/%m/%d(%a) %H:%M")
  .main_center_thread_lower-message
    - if message.content.present?
      %p.lower-message__content
        = message.content
    = image_tag message.image.url, class: "lower-message__image" if message.image.present?

app/views/messages/_top_page.html.haml
.top_page
  .side_bar
    .side_bar_top
      .side_bar_top_image
        - if @group.icon?
          %img#topicon{:src => @group.icon}/
        - else
          .none_photo_side
            %img.top_none{:src => '/error/akatyan02.png'}/

    .side_bar_data
      .side_bar_data_name
        = @group.name
      .side_bar_data_birthday
        = @group.birthday
        生
    .side_bar_under
      .side_bar_under_image
        - if @group.meimei?
          %img#topmeimei{:src => @group.meimei}/
        - else
          .none_photo_under
            %img.top_none{:src => '/error/meimei.jpeg'}/
    .side_bar_bottom
      .side_bar_bottom_message
    .toppage_edit_btn
      =link_to edit_group_path(@group), class: "edit_btn" do
        %button.album_edit.btn 編集


  .toppage
    .toppage_name
      = @group.name
      のお部屋
    .toppage_content
      .toppage_content_data
        .toppage_content_data_image
          - if @group.image?
            %img#top_photo{:src => @group.image}/
          - else
            .none_photo_image
              %img.album_none1{:src => '/error/akatyan02.png'}/
      .toppage_content_title
        ママ・パパこれからずっとよろしくね
      .toppage_content_comment

app/views/messages/index.html.haml
%body.body
  %header
    %h1.head Baby memorY
    = render 'groups/user_edit'
  %ul.tab
    %li.select TOP Page
    %li ０〜2ヶ月
    %li ３〜5ヶ月
    %li ６〜8ヶ月
    %li ９〜11ヶ月
    %li １歳〜
    %li アルバム
    %li 設定
  %ul.content
    %li= render 'top_page'
    %li.hide= render 'album02'
    %li.hide= render 'album35'
    %li.hide= render 'album68'
    %li.hide= render 'album911'
    %li.hide= render 'album1'
    %li.hide= render "main_chat"
    %li.hide= render 'groups/setting'
  %footer.footer Copyright BabymemorY 2019.

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'